// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesManagementMVC.Data;

namespace SalesManagementMVC.Migrations
{
    [DbContext(typeof(SalesManagementMVCContext))]
    [Migration("20201223012043_NovoAtributoOrderItem")]
    partial class NovoAtributoOrderItem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SalesManagementMVC.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("CustomerId");

                    b.Property<string>("Name");

                    b.Property<int>("PaymentForm");

                    b.Property<int>("Status");

                    b.Property<double>("Total");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("SalesManagementMVC.Models.OrderItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<int>("OrderId");

                    b.Property<string>("OrderId1");

                    b.Property<string>("ProductName");

                    b.Property<double>("Total");

                    b.Property<double>("UnitValue");

                    b.HasKey("Id");

                    b.HasIndex("OrderId1");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("SalesManagementMVC.Models.OrderItem", b =>
                {
                    b.HasOne("SalesManagementMVC.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId1");
                });
#pragma warning restore 612, 618
        }
    }
}
